/*
 * Copyright (c) 2016. Vodori, Inc.  All rights reserved.
 *
 * This software is not open source and license for its use and
 * modification can only be granted through an agreement with
 * Vodori, Inc.
 *
 * http://www.vodori.com
 */
package parts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Names {

    private static List<String> names = Arrays.asList(
            "James",
            "John",
            "Robert",
            "Michael",
            "William",
            "David",
            "Mary",
            "Richard",
            "Joseph",
            "Thomas",
            "Charles",
            "Christopher",
            "Daniel",
            "Patricia",
            "Matthew",
            "Jennifer",
            "Elizabeth",
            "Linda",
            "Barbara",
            "Anthony",
            "Donald",
            "Mark",
            "Paul",
            "Steven",
            "George",
            "Kenneth",
            "Andrew",
            "Joshua",
            "Edward",
            "Brian",
            "Kevin",
            "Susan",
            "Ronald",
            "Timothy",
            "Jessica",
            "Margaret",
            "Jason",
            "Sarah",
            "Karen",
            "Nancy",
            "Jeffrey",
            "Betty",
            "Dorothy",
            "Lisa",
            "Ryan",
            "Gary",
            "Jacob",
            "Nicholas",
            "Sandra",
            "Eric",
            "Stephen",
            "Ashley",
            "Kimberly",
            "Donna",
            "Jonathan",
            "Carol",
            "Michelle",
            "Larry",
            "Emily",
            "Helen",
            "Amanda",
            "Scott",
            "Frank",
            "Justin",
            "Melissa",
            "Brandon",
            "Deborah",
            "Stephanie",
            "Laura",
            "Rebecca",
            "Sharon",
            "Raymond",
            "Cynthia",
            "Gregory",
            "Kathleen",
            "Samuel",
            "Benjamin",
            "Shirley",
            "Amy",
            "Anna",
            "Patrick",
            "Angela",
            "Ruth",
            "Jack",
            "Alexander",
            "Dennis",
            "Brenda",
            "Jerry",
            "Pamela",
            "Virginia",
            "Katherine",
            "Nicole",
            "Catherine",
            "Tyler",
            "Christine",
            "Samantha",
            "Aaron",
            "Henry",
            "Douglas",
            "Debra",
            "Janet",
            "Peter",
            "Carolyn",
            "Rachel",
            "Jose",
            "Adam",
            "Heather",
            "Maria",
            "Zachary",
            "Walter",
            "Nathan",
            "Diane",
            "Emma",
            "Julie",
            "Joyce",
            "Harold",
            "Frances",
            "Evelyn",
            "Joan",
            "Kyle",
            "Christina",
            "Kelly",
            "Martha",
            "Lauren",
            "Victoria",
            "Carl",
            "Judith",
            "Arthur",
            "Gerald",
            "Cheryl",
            "Megan",
            "Alice",
            "Roger",
            "Ann",
            "Keith",
            "Jean",
            "Jeremy",
            "Doris",
            "Andrea",
            "Lawrence",
            "Terry",
            "Marie",
            "Kathryn",
            "Jacqueline",
            "Sean",
            "Albert",
            "Gloria",
            "Joe",
            "Teresa",
            "Hannah",
            "Sara",
            "Janice",
            "Christian",
            "Austin",
            "Willie",
            "Julia",
            "Olivia",
            "Jesse",
            "Ethan",
            "Grace",
            "Billy",
            "Rose",
            "Theresa",
            "Judy",
            "Bruce",
            "Bryan",
            "Beverly",
            "Denise",
            "Marilyn",
            "Ralph",
            "Amber",
            "Danielle",
            "Roy",
            "Jordan",
            "Brittany",
            "Madison",
            "Diana",
            "Eugene",
            "Jane",
            "Wayne",
            "Louis",
            "Dylan",
            "Alan",
            "Lori",
            "Mildred",
            "Juan",
            "Tiffany",
            "Noah",
            "Natalie",
            "Russell",
            "Abigail",
            "Kathy",
            "Harry",
            "Randy",
            "Philip",
            "Vincent",
            "Gabriel",
            "Bobby",
            "Johnny",
            "Howard"
    );

    private static List<String> namesSorted = new ArrayList<>(names);

    static {
        Collections.sort(namesSorted);
    }

    public static List<String> getNames() {
        return names;
    }

    public static List<String> getNamesAlphabetical() {
        return namesSorted;
    }
}
